services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
    - ${PORT}:${PORT}
    environment:
      APP_ENV: prod
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_URL: /app/db/reka.db
      DATABASE_DRIVER: sqlite
    volumes:
    - sqlite:/app/db
    networks:
    - blueprint
volumes:
  sqlite:
networks:
  blueprint:
