name: Publish to Docker Hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:


permissions:
  contents: write

jobs:
  # ==========================
  #  Publish Docker Image
  # ==========================
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/reka:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/reka:${{ github.sha }}
